const details = [
  {
    name: "Shah Rukh Khan",
    image:
      "https://i.pinimg.com/originals/99/d3/60/99d36030af8c671082beebeed469d5f7.jpg",
    summary: ` Shah Rukh Khan, also known by the initials SRK, is an Indian actor, film producer, and television personality. He was born on November 2, 1965, in New Delhi, India.\n
Khan began his acting career in the late 1980s and became a household name in the 1990s with his roles in successful films such as "Dilwale Dulhania Le Jayenge" (1995) and "Kuch Kuch Hota Hai" (1998). He has since appeared in numerous critically acclaimed and commercially successful films, including "Devdas" (2002), "Chak De! India" (2007), and "My Name Is Khan" (2010).\n
Aside from acting, Khan is also a successful film producer and has produced several films under his production company, Red Chillies Entertainment. He has also been a television host, including hosting the popular Indian version of the game show "Who Wants to Be a Millionaire?" called "Kaun Banega Crorepati" in 2007.\n
Khan is considered one of the most successful and influential actors in the Indian film industry. He has won numerous awards for his performances, including 14 Filmfare Awards, which is the most won by any actor in the history of the awards. In 2005, he was honored with the Padma Shri, which is one of the highest civilian awards in India`,
    DOB: " November 2,1965 ",
    DOBA: "New Delhi,India",

    movies: [
      {
        name: "Zero",
        dateOfRelease: "December 21, 2018",
        boxOfficeEarning: "₹178.84 crore",
        verdict: "Flop",
        index: 1,
      },
      {
        name: "Jab Harry Met Sejal",
        dateOfRelease: "August 4, 2017",
        boxOfficeEarning: "₹146 crore",
        verdict: "Flop",
        index: 2,
      },
      {
        name: "Raees",
        dateOfRelease: "January 25, 2017",
        boxOfficeEarning: "₹307 crore",
        verdict: "Super Hit",
        index: 3,
      },
      {
        name: "Dear Zindagi",
        dateOfRelease: "November 25, 2016",
        boxOfficeEarning: "₹139 crore",
        verdict: "Hit",
        index: 4,
      },
      {
        name: "Fan",
        dateOfRelease: "April 15, 2016",
        boxOfficeEarning: "₹188 crore",
        verdict: "Average",
        index: 5,
      },
      {
        name: "Dilwale",
        dateOfRelease: "December 18, 2015",
        boxOfficeEarning: "₹394 crore",
        verdict: "Hit",
        index: 6,
      },
      {
        name: "Happy New Year",
        dateOfRelease: "October 24, 2014",
        boxOfficeEarning: "₹385 crore",
        verdict: "Super Hit",
        index: 7,
      },
      {
        name: "Chennai Express",
        dateOfRelease: "August 8, 2013",
        boxOfficeEarning: "₹423 crore",
        verdict: "Blockbuster",
        index: 8,
      },
      {
        name: "Jab Tak Hai Jaan",
        dateOfRelease: "November 13, 2012",
        boxOfficeEarning: "₹211.59 crore",
        verdict: "Hit",
        index: 9,
      },
      {
        name: "Don 2",
        dateOfRelease: "December 23, 2011",
        boxOfficeEarning: "₹229.5 crore",
        verdict: "Hit",
        index: 10,
      },
      {
        name: "Ra.One",
        dateOfRelease: "October 26, 2011",
        boxOfficeEarning: "₹240 crore",
        verdict: "Hit",
        index: 11,
      },
      {
        name: "Dulha Mil Gaya",
        dateOfRelease: "January 8, 2010",
        boxOfficeEarning: "₹9.6 crore",
        verdict: "Flop",
        index: 12,
      },
      {
        name: "My Name Is Khan",
        dateOfRelease: "February 12, 2010",
        boxOfficeEarning: "₹205 crore",
        verdict: "Blockbuster",
        index: 13,
      },
      {
        name: "Luck by Chance",
        dateOfRelease: "January 30, 2009",
        boxOfficeEarning: "₹12.13 crore",
        verdict: "Flop",
        index: 14,
      },
      {
        name: "Billu",
        dateOfRelease: "February 13, 2009",
        boxOfficeEarning: "₹23.45 crore",
        verdict: "Average",
        index: 15,
      },
      {
        name: "Rab Ne Bana Di Jodi",
        dateOfRelease: "December 12, 2008",
        boxOfficeEarning: "₹206.5 crore",
        verdict: "Blockbuster",
        index: 16,
      },
      {
        name: "Bhoothnath",
        dateOfRelease: "May 9, 2008",
        boxOfficeEarning: "₹44 crore",
        verdict: "Hit",
        index: 17,
      },
      {
        name: "Om Shanti Om",
        dateOfRelease: "November 9, 2007",
        boxOfficeEarning: "₹149.9 crore",
        verdict: "Blockbuster",
        index: 18,
      },
      {
        name: "Chak De! India",
        dateOfRelease: "August 10, 2007",
        boxOfficeEarning: "₹152 crore",
        verdict: "Blockbuster",
        index: 19,
      },
      {
        name: "Kabhi Alvida Naa Kehna",
        dateOfRelease: "August 11, 2006",
        boxOfficeEarning: "₹112.85 crore",
        verdict: "Hit",
        index: 20,
      },
      {
        name: "Don - The Chase Begins Again",
        dateOfRelease: "October 20, 2006",
        boxOfficeEarning: "₹106 crore",
        verdict: "Hit",
        index: 21,
      },
      {
        name: "Dilwale Dulhania Le Jayenge (re-release)",
        dateOfRelease: "February 4, 2005",
        boxOfficeEarning: "₹12.06 crore",
        verdict: "Blockbuster",
        index: 22,
      },
      {
        name: "Paheli",
        dateOfRelease: "June 24, 2005",
        boxOfficeEarning: "₹25.83 crore",
        verdict: "Average",
        index: 23,
      },
      {
        name: "Veer-Zaara",
        dateOfRelease: "November 12, 2004",
        boxOfficeEarning: "₹97.5 crore",
        verdict: "Super Hit",
        index: 24,
      },
      {
        name: "Main Hoon Na",
        dateOfRelease: "April 30, 2004",
        boxOfficeEarning: "₹82.2 crore",
        verdict: "Hit",
        index: 25,
      },
      {
        name: "Yeh Lamhe Judaai Ke",
        dateOfRelease: "April 9, 2003",
        boxOfficeEarning: "₹0.21 crore",
        verdict: "Disaster",
        index: 26,
      },
      {
        name: "Chalte Chalte",
        dateOfRelease: "June 13, 2003",
        boxOfficeEarning: "₹33.68 crore",
        verdict: "Hit",
        index: 27,
      },
      {
        name: "Kal Ho Naa Ho",
        dateOfRelease: "November 28, 2003",
        boxOfficeEarning: "₹86.95 crore",
        verdict: "Hit",
        index: 28,
      },
      {
        name: "Saathiya",
        dateOfRelease: "December 20, 2002",
        boxOfficeEarning: "₹22.54 crore",
        verdict: "Hit",
        index: 29,
      },
      {
        name: "Shakti: The Power",
        dateOfRelease: "September 20, 2002",
        boxOfficeEarning: "₹10.11 crore",
        verdict: "Flop",
        index: 30,
      },
      {
        name: "Devdas",
        dateOfRelease: "July 12, 2002",
        boxOfficeEarning: "₹102.5 crore",
        verdict: "Hit",
        index: 31,
      },
      {
        name: "Asoka",
        dateOfRelease: "October 26, 2001",
        boxOfficeEarning: "₹15.16 crore",
        verdict: "Flop",
        index: 32,
      },
      {
        name: "Kabhi Khushi Kabhie Gham",
        dateOfRelease: "December 14, 2001",
        boxOfficeEarning: "₹135.52 crore",
        verdict: "Blockbuster",
        index: 33,
      },
      {
        name: "Gaja Gamini",
        dateOfRelease: "November 1, 2000",
        boxOfficeEarning: "₹0.04 crore",
        verdict: "Flop",
        index: 34,
      },
      {
        name: "Har Dil Jo Pyar Karega",
        dateOfRelease: "August 4, 2000",
        boxOfficeEarning: "₹28.67 crore",
        verdict: "Average",
        index: 35,
      },
      {
        name: "Mohabbatein",
        dateOfRelease: "October 27, 2000",
        boxOfficeEarning: "₹87.37 crore",
        verdict: "Blockbuster",
        index: 36,
      },
      {
        name: "Baadshah",
        dateOfRelease: "August 27, 1999",
        boxOfficeEarning: "₹29.24 crore",
        verdict: "Average",
        index: 38,
      },
      {
        name: "Dil To Pagal Hai",
        dateOfRelease: "October 30, 1998",
        boxOfficeEarning: "₹72.48 crore",
        verdict: "Blockbuster",
        index: 39,
      },
      {
        name: "Pardes",
        dateOfRelease: "August 8, 1998",
        boxOfficeEarning: "₹43.17 crore",
        verdict: "Hit",
        index: 40,
      },
      {
        name: "Duplicate",
        dateOfRelease: "May 8, 1998",
        boxOfficeEarning: "₹16.32 crore",
        verdict: "Below Average",
        index: 41,
      },
      {
        name: "Dil Se..",
        dateOfRelease: "August 21, 1998",
        boxOfficeEarning: "₹33.32 crore",
        verdict: "Semi-Hit",
        index: 42,
      },
      {
        name: "Dil To Pagal Hai",
        dateOfRelease: "October 31, 1997",
        boxOfficeEarning: "₹72.26 crore",
        verdict: "Blockbuster",
        index: 43,
      },
      {
        name: "Pardes",
        dateOfRelease: "August 8, 1997",
        boxOfficeEarning: "₹45.86 crore",
        verdict: "Hit",
        index: 44,
      },
      {
        name: "Yes Boss",
        dateOfRelease: "July 18, 1997",
        boxOfficeEarning: "₹20.75 crore",
        verdict: "Super Hit",
        index: 45,
      },
      {
        name: "Ram Jaane",
        dateOfRelease: "November 29, 1996",
        boxOfficeEarning: "₹9.25 crore",
        verdict: "Below Average",
        index: 46,
      },
      {
        name: "Army",
        dateOfRelease: "October 28, 1996",
        boxOfficeEarning: "₹6.25 crore",
        verdict: "Flop",
        index: 47,
      },
      {
        name: "Dushman Duniya Ka",
        dateOfRelease: "September 20, 1996",
        boxOfficeEarning: "Unknown",
        verdict: "Flop",
        index: 48,
      },
      {
        name: "Chaahat",
        dateOfRelease: "June 6, 1996",
        boxOfficeEarning: "₹7.33 crore",
        verdict: "Flop",
        index: 49,
      },
      {
        name: "Dilwale Dulhania Le Jayenge",
        dateOfRelease: "October 20, 1995",
        boxOfficeEarning: "₹106.39 crore",
        verdict: "All-Time Blockbuster",
        index: 50,
      },
      {
        name: "Oh Darling! Yeh Hai India!",
        dateOfRelease: "August 11, 1995",
        boxOfficeEarning: "₹2.26 crore",
        verdict: "Flop",
        index: 51,
      },
      {
        name: "Guddu",
        dateOfRelease: "September 11, 1995",
        boxOfficeEarning: "Unknown",
        verdict: "Flop",
        index: 52,
      },
      {
        name: "Zamaana Deewana",
        dateOfRelease: "July 28, 1995",
        boxOfficeEarning: "₹3.28 crore",
        verdict: "Flop",
        index: 53,
      },
      {
        name: "Karan Arjun",
        dateOfRelease: "January 13, 1995",
        boxOfficeEarning: "₹52.45 crore",
        verdict: "Blockbuster",
        index: 54,
      },
      {
        name: "Anjaam",
        dateOfRelease: "April 22, 1994",
        boxOfficeEarning: "₹3.75 crore",
        verdict: "Flop",
        index: 55,
      },
      {
        name: "Kabhi Haan Kabhi Naa",
        dateOfRelease: "February 25, 1994",
        boxOfficeEarning: "₹3.25 crore",
        verdict: "Average",
        index: 56,
      },
      {
        name: "Darr",
        dateOfRelease: "December 24, 1993",
        boxOfficeEarning: "₹22.5 crore",
        verdict: "Super Hit",
        index: 57,
      },
      {
        name: "Baazigar",
        dateOfRelease: "November 12, 1993",
        boxOfficeEarning: "₹14.5 crore",
        verdict: "Hit",
        index: 58,
      },
      {
        name: "Raju Ban Gaya Gentleman",
        dateOfRelease: "November 13, 1992",
        boxOfficeEarning: "₹6 crore",
        verdict: "Hit",
        index: 59,
      },
      {
        name: "Chamatkar",
        dateOfRelease: "July 8, 1992",
        boxOfficeEarning: "₹5.5 crore",
        verdict: "Average",
        index: 60,
      },
      {
        name: "Deewana",
        dateOfRelease: "June 25, 1992",
        boxOfficeEarning: "₹19 crore",
        verdict: "Super Hit",
        index: 61,
      },
    ],
  },
];
export default details;
